extends:
  - '@commitlint/config-conventional'
  # - 'gitmoji'
rules:
  header-max-length: [1, 'always', 72]
  type-enum:
  - 2
  - always
  - - feat
    - fix
    - docs
    - style
    - refactor
    - perf
    - test
    - chore
    - breaking
help: |
  **Possible types**:
  `feat`:       Adds a new feature.
  `fix`:        Solves a bug.
  `docs`:       Adds or alters documentation. (example scopes: readme, worker, code_of_conduct, contributors)
  `style`:      Improves formatting, white-space.
  `refactor`:   Rewrites code without feature, performance or bug changes.
  `perf`:       Improves performance.
  `test`:       Adds or modifies tests. (example scopes: functionals, unit-tests)
  `chore`:      No production code change. Updating grunt tasks etc;
  `breaking`:   Rewrites code but it brakes backwards compatibility.