extends:
  - '@commitlint/config-conventional'
rules:
  header-max-length: [1, 'always', 72]
  type-enum:
  - 2
  - always
  - - fix
    - feat
    - docs
    - style
    - refactor
    - perf
    - test
    - build
    - ci
help: |
  **Possible types**:
  `fix`:      A bug fix. Correlates with PATCH in SemVer
  `feat`:     A new feature. Correlates with MINOR in SemVer
  `docs`:     Documentation only changes
  `style`:    Changes that do not affect the meaning of the code (white-space, format)
  `refactor`: A code change that neither fixes a bug nor adds a feature
  `perf`:     A code change that improves performance
  `test`:     Adding missing or correcting existing tests
  `build`:    Changes that affect the build system or external dependencies
  `ci`:       Changes to our CI configuration files and scripts