build:
    image: latest
conda:
    file: docs/environment.yml
python:
    version: 3.7
    install:
      - method: pip
        path: sphinxcontrib.yt
      - method: setuptools  
        path: blendernc
formats: []