language: python

services:
  - docker

python:
  - '3.7'

services:
  - docker

before_install:
- docker pull nytimes/blender:latest
- docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:latest /bin/sh -c; cd blendernc ; ls; bash ./build-test.sh

script:
- ./build-test.sh