language: bash

services:
  - docker

before_install:
- docker pull nytimes/blender:latest
- docker run -w /addon-test -v ${pwd}:/addon-test -t nytimes/blender:latest /bin/bash

script:
- $BLENDERPY -m ensurepip --default-pip
- wget https://raw.githubusercontent.com/blendernc/blendernc/master/requirements.txt
- $BLENDERPY -m pip install -r requirements.txt
- blender --background --python ./bpy_activate_addon.py