language: python

services:
  - docker

python:
  - '3.7'

services:
  - docker

before_install:
  - docker pull nytimes/blender:latest
  - docker pull nytimes/blender:2.83-cpu-ubuntu18.04
  - zip -r .github/travis/blendernc.zip ../blendernc
  - cd .github/travis/

script:
  - docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:latest /bin/sh -c "bash ./build-test.sh"

  - docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:2.83-cpu-ubuntu18.04 /bin/sh -c "bash ./build-test.sh"