language: python

services:
  - docker

python:
  - '3.7'

services:
  - docker

before_install:
- docker pull nytimes/blender:latest
- zip -r .github/travis/blendernc_build.zip .
- cd .github/travis/
- docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:latest /bin/sh -c "bash ./build-test.sh"