language: python

# safelist
branches:
  only:
  - master
  - docs
  - stable

services:
  - docker

python:
  - '3.7'

services:
  - docker

before_install:
  - docker pull nytimes/blender:latest
  - docker pull nytimes/blender:2.91-cpu-ubuntu18.04
  - docker pull nytimes/blender:2.83-cpu-ubuntu18.04
  - zip -r .github/travis/blendernc.zip ../blendernc
  - pip install -r requirements.txt
  - pip install -e .
  - cd .github/travis/
  - wget https://raw.githubusercontent.com/blendernc/blendernc/master/requirements.txt

script:
  - docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:latest /bin/sh -c "bash ./build-test.sh"

  - docker run -w /addon-test --rm -it -v $(pwd):/addon-test -t nytimes/blender:2.83-cpu-ubuntu18.04 /bin/sh -c "bash ./build-test.sh"