language: bash

services:
  - docker

before_install:
- docker pull nytimes/blender:latest
- docker run \
           -w /addon-test \
           -v $(pwd):/addon-test \
           -t nytimes/blender:latest \
           /bin/bash
- 

script:
- blender --background --python ./bpy_activate_addon.py