name: Release ZIP file
on:
  push:
    branches:
      - test
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: creates output
        run:  |
          rsync -arv  ./blendernc/ ./release
    - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'blendernc'
          destination-github-username: 'release'
          destination-repository-name: 'blendernc-zip-install'
          user-email: josue.martinezmoreno@anu.edu.au
          target-branch: main