name: Test

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest", "2.92-cpu-ubuntu18.04", "2.83-cpu-ubuntu18.04"]
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v1

      - name: Install coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Pull Blender Docker Image
        run: |
          docker pull nytimes/blender: ${{ matrix.node }}

job:
  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node: ["latest", "2.92-cpu-ubuntu18.04", "2.83-cpu-ubuntu18.04"]
    steps:
      - name: Test addon
        run: |
          docker run -w /addon/blendernc --rm --mount type=bind,source="$(pwd)",target=/addon/blendernc -t nytimes/blender:${{ matrix.node }} /bin/sh -c "bash ./tests/build-test.sh"

      - name: Report coverage
        run: |
          cd ./tests/
          coverage combine
          coverage report
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/coverage.xml
          flags: unittests