name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Blender Docker Image and test addon
        run: |
          docker pull nytimes/blender:latest
          docker pull nytimes/blender:2.83-cpu-ubuntu18.04
          cd .github/travis/
          zip blendernc.zip -r ../../blendernc
          docker run -w /addon-test --rm -v $(pwd):/addon-test -t nytimes/blender:latest /bin/sh -c "bash ./build-test.sh"
          docker run -w /addon-test --rm -v $(pwd):/addon-test -t nytimes/blender:2.83-cpu-ubuntu18.04 /bin/sh -c "bash ./build-test.sh"