name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Blender Docker Image and test addon
        run: |
          docker pull nytimes/blender:latest
          docker pull nytimes/blender:2.83-cpu-ubuntu18.04
          zip ./tests/blendernc.zip -r ../blendernc


          docker run -w /blendernc --rm -v $(pwd):/blendernc -t nytimes/blender:latest /bin/sh -c "bash ./tests/build-test.sh"
          docker run -w /blendernc --rm -v $(pwd):/blendernc -t nytimes/blender:2.83-cpu-ubuntu18.04 /bin/sh -c "bash ./tests/build-test.sh"